### ISSUE TITLE
Installation problem on Windows 11

### ISSUE THREAD

**Issue by srbrodzik** [samuelleblanc/fp#19]
I just tried to install and got this when trying to run ml.  The end of the installation completed without error, but when I tried to run ml I got a bunch of errors.  Do I need to change my PATH variable?  Now that I've closed that command window and opened another, I can't even find ml.  Suggestions?

Stacy

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: done

(ml) C:\Users\impacts\miniforge3\condabin>ml
Traceback (most recent call last):
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\movinglines\ml.py", line 127, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\impacts\miniforge3\envs\ml\Scripts\ml-script.py", line 6, in <module>
    from movinglines import main
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\movinglines\__init__.py", line 24, in <module>
    from .ml import Create_interaction as main
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\movinglines\ml.py", line 130, in <module>
    from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\__init__.py", line 109, in <module>
    from . import _api, _version, cbook, docstring, rcsetup
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\rcsetup.py", line 27, in <module>
    from matplotlib.colors import Colormap, is_color_like
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\matplotlib\colors.py", line 51, in <module>
    from PIL import Image
  File "C:\Users\impacts\miniforge3\envs\ml\lib\site-packages\PIL\Image.py", line 114, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.

(ml) C:\Users\impacts\miniforge3\condabin>
(

**Comment by samuelleblanc** [comment]
This is strange, can you make sure you've made an environment based on python 3.9?

I've also updated the requirements for packages on conda, can you update to newest install (v1.49) there?
https://anaconda.org/samuelleblanc/movinglines

**Comment by srbrodzik** [comment]
I'll take a look at how I set things up.  It's been awhile and I don't
remember what I did.

Stacy

**Comment by srbrodzik** [comment]
Hi Sam,

I just ran the following commands:

conda create -n ml python=3.9
conda activate ml
conda install samuelleblanc::movinglines

After the last one, I got the following error.  Can you tell me what I'm
doing wrong?

Stacy


(ml) C:\Users\impacts>conda install samuelleblanc::movinglines
Channels:
 - defaults
 - samuelleblanc
Platform: win-64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from
current channels:

  - samuelleblanc::movinglines

Current channels:

  - defaults
  - https://conda.anaconda.org/samuelleblanc

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by samuelleblanc** [comment]
This is similar to what was also found by others. I amended the readme to include the need to add the conda-forge channel for the dependencies for the conda installations (mamba has this already set up).

conda config --add channels conda-forge

Does that work?

**Comment by srbrodzik** [comment]
Yes, that seems to work.  This time when I type the ml command I get the
expected GUI.

Thanks for the help.

Stacy

**Comment by samuelleblanc** [comment]
Great!
